name: Auto Merge Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - dev  # or the base branch you want to target

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Check for merge conflicts
        run: |
          git fetch origin main  # Fetch the latest changes from the target branch (dev)
          git checkout ${{ github.head_ref }}
          git merge --no-ff origin/dev --no-commit || echo "Merge conflicts detected"

      - name: Merge PR if no conflicts
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          response=$(curl -X PUT \
            -H "Authorization: token $TOKEN" \
            -d '{"commit_message": "Auto-merge PR #'"$PR_NUMBER"'", "merge_method": "merge"}' \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge)

          # Debug: Print the API response
          echo "Merge response: $response"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
